### ISSUE TITLE
how to watch json file and merge

### ISSUE THREAD

**Issue by thienhoanguit** [marcioggs/ng-i18n-merge-files#12]
I use the command: "start": "npx ng-i18n-merge-files -f json & ng serve" to run debug app

But when I change *.json file, the website just reload but don't merge file again

So, My label is show: "translations.User.Username" instead of Username value

how to merge translation file when I edited

**Comment by marcioggs** [comment]
Hi @thienhoanguit,
Thank you for using the library!

From my experience, Angular's ng serve only applies translations when it starts, so any changes to the translation files require a restart for them to take effect.
I tested your scenario using the sample app in this repository. After modifying the JSON file (either the individual files or the final merged file), the application didn't rebuild, and the labels continued to display the old text instead of the translation key, unlike what you encountered.
